
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'
#
development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  database: my_database_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  database:  my_database_development
  pool: 5
  username:
  password:
